Added a minimum player fake player count, and a constant count.
jpenilla/MiniMOTD pull request #50
Opened 2021-03-12 03:46 UTC by pandather

This lets me make my player count 69/420. Also my first open source contribution! :D

2021-03-25 14:53 UTC, pandather commented
Should I change anything to edit this pull request?

2021-04-06 02:41 UTC, jpenilla requested changes

2021-04-06 02:41 UTC, jpenilla commented on common/src/main/java/xyz/jpenilla/minimotd/common/config/MiniMOTDConfig.java
> +        + " - minimum: The player count the maximum of this or the number of online players\n"
Please improve the grammar a bit here

2021-04-06 02:41 UTC, jpenilla commented on common/src/main/java/xyz/jpenilla/minimotd/common/config/MiniMOTDConfig.java
>          + "\n"
GitHub won't allow me to comment on the line above this one, however the line above this one needs to be updated to include `constant` and `minimum`.

2021-04-06 02:41 UTC, jpenilla commented on common/src/main/java/xyz/jpenilla/minimotd/common/config/MiniMOTDConfig.java
> +        + "     ex: fakePlayers: \"42!\"\n"
Prefer `=` instead of `!`.

2021-04-06 02:41 UTC, jpenilla commented on common/src/main/java/xyz/jpenilla/minimotd/common/MiniMOTD.java
> +        } else if (fakePlayersConfigString.contains("!")) {
Prefer `=` instead of `!`.

2021-04-06 02:41 UTC, jpenilla commented on common/src/main/java/xyz/jpenilla/minimotd/common/MiniMOTD.java
> +          final int shownPlayers = Integer.parseInt(fakePlayersConfigString.replace("!", ""));
Prefer `=` instead of `!`.

2021-04-06 17:06 UTC, pandather commented
okay, I added the requested changes

2021-04-06 23:42 UTC, jpenilla approved these changes

2021-04-06 23:43 UTC, merged